mode = "dark"

accent = "#97ccf8"
selection = "#004b71"
muted = "#c1c7ce"

hyprland_inactive_border = "rgba(8b9198aa)"
hyprland_active_border = "rgba(97ccf8ff) rgba(d0c0e8ff) rgba(004b71ff) 45deg"

background = "#101417"
dark_background = "#0b0f12"
darker_background = "#090c0f"
lighter_background = "#262a2e"

foreground = "#e0e3e8"
dark_foreground = "#c1c7ce"
light_foreground = "#e0e3e8"
bright_foreground = "#e0e3e8"

red = "#f38ba8"
yellow = "#f9e2af"
orange = "#f6b6ab"
green = "#a6e3a1"
cyan = "#94e2d5"
blue = "#89b4fa"
magenta = "#f5c2e7"
brown = "#7b5b55"
bright_red = "#f38ba8"
bright_yellow = "#f9e2af"
bright_green = "#a6e3a1"
bright_cyan = "#94e2d5"
bright_blue = "#89b4fa"
bright_magenta = "#f5c2e7"
