mode = "dark"

accent = "#bfc2ff"
selection = "#3c4080"
muted = "#ddc1ae"

background = "#1b110a"
dark_background = "#150c06"
darker_background = "#120a05"
lighter_background = "#33281f"

foreground = "#f3dfd2"
dark_foreground = "#ddc1ae"
light_foreground = "#f3dfd2"
bright_foreground = "#f3dfd2"

red = "#f38ba8"
yellow = "#f9e2af"
orange = "#f6b6ab"
green = "#a6e3a1"
cyan = "#94e2d5"
blue = "#89b4fa"
magenta = "#f5c2e7"
brown = "#7b5b55"
bright_red = "#f38ba8"
bright_yellow = "#f9e2af"
bright_green = "#a6e3a1"
bright_cyan = "#94e2d5"
bright_blue = "#89b4fa"
bright_magenta = "#f5c2e7"
